### PR TITLE
feat: Exchange subgraph (lite version)

### PR DESCRIPTION
**Pull request by ChefKai**

### CODE REVIEW

**Comment by pnghai** [comment]
@ChefKai hi, is this the branch for https://thegraph.com/explorer/subgraph/pancakeswap/exchange-lite? 
Where was the code for PairSimple , Factory, etc?

**Comment by ChefKai** [comment]
> @ChefKai hi, is this the branch for https://thegraph.com/explorer/subgraph/pancakeswap/exchange-lite?
> Where was the code for PairSimple , Factory, etc?

Hello, yes this is the PR associated to this subgraph, it was a work-in-progress to test multiple ways to reduce indexing time, and multiple underlying changes were made to it since then (but not to the interface), given the amount of pairs and events related to the Factory contract and LP's

**Comment by pnghai** [comment]
@ChefKai I noticed that https://github.com/pancakeswap/pancake-subgraph/pull/27/files#diff-640a3babb9798a12831459e8d098f1ff64bb861f6ebb9145fbbbf1a61072e71bR105 is missing derivedUSD, yet your api project is relied on this (https://github.com/pancakeswap/pancake-info-api/blob/develop/utils/generated/subgraph.ts#L548)

Will this change be reflected to https://github.com/pancakeswap/pancake-info-api as well?

**Comment by ChefKai** [comment]
> @ChefKai I noticed that https://github.com/pancakeswap/pancake-subgraph/pull/27/files#diff-640a3babb9798a12831459e8d098f1ff64bb861f6ebb9145fbbbf1a61072e71bR105 is missing derivedUSD, yet your api project is relied on this (https://github.com/pancakeswap/pancake-info-api/blob/develop/utils/generated/subgraph.ts#L548)
> 
> Will this change be reflected to https://github.com/pancakeswap/pancake-info-api as well?

We've removed the logic from the subgraph and will pull the data from the pair directly, to avoid loading the entity on every `Sync` event to speed up the sync process.

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by MaryJaneLove4 — COMMENTED** [review]
It´s really goo

**Review by MaryJaneLove4 — COMMENTED** [review]
Miss line 11, 28, 29

**Review by MaryJaneLove4 — APPROVED** [review]
Miss   src/exchange-lite/factory.ts

**Review by MaryJaneLove4 — COMMENTED** [review]
OOO thanks

**Pull request closed without merging**
